### PR TITLE
Fixed anchor to ginkgo gomock integration

### PR DESCRIPTION
**Pull request by daniellavoie**

### CODE REVIEW

**Comment by brysgo** [comment]
Wow, thanks for this, I'll take a look. I haven't touched this in like 5 years, but I'm glad you were able to use it.

Also, it may take me a little getting up to speed.

**Comment by brysgo** [comment]
Ah, just a readme change, easier.

**Comment by brysgo** [comment]
Also, just read the readme, so I'm glad you aren't using it :-D

**Comment by daniellavoie** [comment]
That is the most elaborate PR I ever pulled off. I would like to take a moment to thank everyone who supported in this massive journey. 😄

**Comment by brysgo** [comment]
🥇 you've earned it

**Pull request merged**
